### PR TITLE
Get: handle "None" values properly

### PR DESCRIPTION
**Pull request by rayrapetyan**
Fix for https://github.com/akesterson/dpath-python/issues/43

### CODE REVIEW

**Comment by rayrapetyan** [comment]
Btw travis fails on a Python 3 init, unrelated to this fix.

**Comment by akesterson** [comment]
Sorry for the delay on this - thanks for sending the patch. I'm dealing with some local tox failures in addition to whatever Travis' problem is, but I'll get this approved & merged sometime this weekend.

**Comment by delijati** [comment]
I know it should be a different feature request, but could be a parameter `default` added? So it would not throw a `KeyError`.

```python
>>> d = {'p': {'a': {'t': {'h': 'value'}}}}
>>> dpath.util.get(d, 'p/a/t/x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  [snip]
    raise KeyError(glob)
KeyError: 'p/a/t/x'
>>> dpath.util.get(d, 'p/a/t/x', default="")
''
```

**Comment by harel** [comment]
This PR raises dpath to perfect status.... Is it going to get merged?

**Comment by akesterson** [comment]
Merged in 10055b5343fba216f730429898021f9ce4bea5e3

**Pull request closed without merging**
