### PR TITLE
Can supply a default return value to get()

### LINKED ISSUE #52: Returning default value
Hey, can you please update the code to send in a default value if an object is not found using the get function.

The function "get" under dpath/util.py can be changed as mentioned below to achieve it

def get(obj, glob, separator="/", default = None):
    """
    Given an object which contains only one possible match for the given glob,
    return the value for the leaf matching the given glob.
    If more than one leaf matches the glob, ValueError is raised. If the glob is
    not found, KeyError is raised.
    """
    ret = None
    for item in search(obj, glob, yielded=True, separator=separator):
        if ret is not None:
            raise ValueError("dpath.util.get() globs must match only one leaf : %s" % glob)
        ret = item[1]
    if ret is None:
        if (default != None):
            ret = default
        else:
            raise KeyError(glob)
    return ret

### PR DESCRIPTION
**Pull request by AWhetter**
This does not introduce any breaking changes.

Closes #52

### CODE REVIEW

**Comment by akesterson** [comment]
Why only add the functionality to get(), what about search()?

**Comment by akesterson** [comment]
Also, why not just catch KeyError and set the default value?

**Comment by AWhetter** [comment]
> what about search()?
I'm on the fence but with `search()`. When searching you're potentially getting back an iterator and it feels weird to populate that with a default value. I haven't come across a use case where I've wanted a default value with `search()`, but I'm happy to add it if you think it would be useful?

> why not just catch KeyError and set the default value?
You could definitely do that, but I think that this is a common enough case and catching an exception an "ugly" enough solution that it's worthwhile. `.get()` exists on a dictionary for this reason, even though you can catch the KeyError from using `dict[]`.

**Comment by calebcase** [comment]
Thanks for the contribution!

**Comment by akesterson** [comment]
Note that this was merged into 2.0, so you will need to pull a 2.x release to get this feature. (We are cutting the first 2.x release today)

**Pull request merged**
